// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.1
// source: rpc_check_if_items_in_stock.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckIfItemsInStockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ItemWithQuantity `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *CheckIfItemsInStockRequest) Reset() {
	*x = CheckIfItemsInStockRequest{}
	mi := &file_rpc_check_if_items_in_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfItemsInStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfItemsInStockRequest) ProtoMessage() {}

func (x *CheckIfItemsInStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_check_if_items_in_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfItemsInStockRequest.ProtoReflect.Descriptor instead.
func (*CheckIfItemsInStockRequest) Descriptor() ([]byte, []int) {
	return file_rpc_check_if_items_in_stock_proto_rawDescGZIP(), []int{0}
}

func (x *CheckIfItemsInStockRequest) GetItems() []*ItemWithQuantity {
	if x != nil {
		return x.Items
	}
	return nil
}

type CheckIfItemsInStockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InStock bool    `protobuf:"varint,1,opt,name=in_stock,json=inStock,proto3" json:"in_stock,omitempty"`
	Items   []*Item `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *CheckIfItemsInStockResponse) Reset() {
	*x = CheckIfItemsInStockResponse{}
	mi := &file_rpc_check_if_items_in_stock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfItemsInStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfItemsInStockResponse) ProtoMessage() {}

func (x *CheckIfItemsInStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_check_if_items_in_stock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfItemsInStockResponse.ProtoReflect.Descriptor instead.
func (*CheckIfItemsInStockResponse) Descriptor() ([]byte, []int) {
	return file_rpc_check_if_items_in_stock_proto_rawDescGZIP(), []int{1}
}

func (x *CheckIfItemsInStockResponse) GetInStock() bool {
	if x != nil {
		return x.InStock
	}
	return false
}

func (x *CheckIfItemsInStockResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_rpc_check_if_items_in_stock_proto protoreflect.FileDescriptor

var file_rpc_check_if_items_in_stock_proto_rawDesc = []byte{
	0x0a, 0x21, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x69, 0x66, 0x5f, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x5f, 0x69, 0x6e, 0x5f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x69, 0x64, 0x6c, 0x1a, 0x0a, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x77, 0x69, 0x74, 0x68, 0x5f,
	0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x49,
	0x0a, 0x1a, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x66, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x49, 0x6e,
	0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x69, 0x64,
	0x6c, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x57, 0x69, 0x74, 0x68, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x59, 0x0a, 0x1b, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x49, 0x66, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x49, 0x6e, 0x53, 0x74, 0x6f, 0x63, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x6e, 0x5f, 0x73,
	0x74, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x6e, 0x53, 0x74,
	0x6f, 0x63, 0x6b, 0x12, 0x1f, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_check_if_items_in_stock_proto_rawDescOnce sync.Once
	file_rpc_check_if_items_in_stock_proto_rawDescData = file_rpc_check_if_items_in_stock_proto_rawDesc
)

func file_rpc_check_if_items_in_stock_proto_rawDescGZIP() []byte {
	file_rpc_check_if_items_in_stock_proto_rawDescOnce.Do(func() {
		file_rpc_check_if_items_in_stock_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_check_if_items_in_stock_proto_rawDescData)
	})
	return file_rpc_check_if_items_in_stock_proto_rawDescData
}

var file_rpc_check_if_items_in_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_check_if_items_in_stock_proto_goTypes = []any{
	(*CheckIfItemsInStockRequest)(nil),  // 0: idl.CheckIfItemsInStockRequest
	(*CheckIfItemsInStockResponse)(nil), // 1: idl.CheckIfItemsInStockResponse
	(*ItemWithQuantity)(nil),            // 2: idl.ItemWithQuantity
	(*Item)(nil),                        // 3: idl.Item
}
var file_rpc_check_if_items_in_stock_proto_depIdxs = []int32{
	2, // 0: idl.CheckIfItemsInStockRequest.items:type_name -> idl.ItemWithQuantity
	3, // 1: idl.CheckIfItemsInStockResponse.items:type_name -> idl.Item
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_check_if_items_in_stock_proto_init() }
func file_rpc_check_if_items_in_stock_proto_init() {
	if File_rpc_check_if_items_in_stock_proto != nil {
		return
	}
	file_item_proto_init()
	file_item_with_quantity_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_check_if_items_in_stock_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_check_if_items_in_stock_proto_goTypes,
		DependencyIndexes: file_rpc_check_if_items_in_stock_proto_depIdxs,
		MessageInfos:      file_rpc_check_if_items_in_stock_proto_msgTypes,
	}.Build()
	File_rpc_check_if_items_in_stock_proto = out.File
	file_rpc_check_if_items_in_stock_proto_rawDesc = nil
	file_rpc_check_if_items_in_stock_proto_goTypes = nil
	file_rpc_check_if_items_in_stock_proto_depIdxs = nil
}
