

order:
  service-name: 订单
  server-to-run: http
  http-addr: 127.0.0.1:8282
  grpc-addr: 127.0.0.1:5002
  log-level: debug
  salt: "secret"
  

stock:
  service-name: 库存
  server-to-run: grpc
  http-addr: 127.0.0.1:8283
  grpc-addr: 127.0.0.1:5003
  log-level: debug
  salt: "secret"

